version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/engine"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/engine/admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
