package registry

// builtinProviders returns the embedded provider catalog.
func builtinProviders() map[string]ProviderInfo {
	return map[string]ProviderInfo{
		"openai": {
			ID:          "openai",
			DisplayName: "OpenAI",
			AuthType:    "api_key",
			Website:     "console.openai.com",
		},
		"anthropic": {
			ID:          "anthropic",
			DisplayName: "Anthropic",
			AuthType:    "api_key",
			Website:     "console.anthropic.com",
		},
		"google": {
			ID:          "google",
			DisplayName: "Google",
			AuthType:    "api_key",
			Website:     "aistudio.google.com",
		},
		"ollama": {
			ID:          "ollama",
			DisplayName: "Ollama",
			AuthType:    "none",
			Website:     "ollama.com",
		},
		"openai_compatible": {
			ID:          "openai_compatible",
			DisplayName: "OpenAI Compatible",
			AuthType:    "api_key",
			Website:     "",
		},
		"openrouter": {
			ID:          "openrouter",
			DisplayName: "OpenRouter",
			AuthType:    "api_key",
			Website:     "openrouter.ai",
		},
		"azure_openai": {
			ID:          "azure_openai",
			DisplayName: "Azure OpenAI",
			AuthType:    "api_key",
			Website:     "portal.azure.com",
		},
		"deepseek": {
			ID:          "deepseek",
			DisplayName: "DeepSeek",
			AuthType:    "api_key",
			Website:     "platform.deepseek.com",
		},
		"mistral": {
			ID:          "mistral",
			DisplayName: "Mistral",
			AuthType:    "api_key",
			Website:     "console.mistral.ai",
		},
		"xai": {
			ID:          "xai",
			DisplayName: "xAI",
			AuthType:    "api_key",
			Website:     "console.x.ai",
		},
		"zai": {
			ID:          "zai",
			DisplayName: "Z.ai (GLM)",
			AuthType:    "api_key",
			Website:     "z.ai",
		},
	}
}

// builtinModels returns the embedded model catalog.
func builtinModels() map[string]ModelInfo {
	return map[string]ModelInfo{
		// --- Tier 1: Orchestrator ---
		"claude-opus-4-6": {
			ID:             "claude-opus-4-6",
			DisplayName:    "Claude Opus 4.6",
			Provider:       "anthropic",
			Tier:           Tier1,
			ContextWindow:  1_000_000,
			MaxOutput:      32_000,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   5.0,
			PricingOutput:  25.0,
			Description:    "Top-tier reasoning model with extended context and vision",
			RecommendedFor: []string{"orchestrator"},
		},
		"claude-sonnet-4-6": {
			ID:             "claude-sonnet-4-6",
			DisplayName:    "Claude Sonnet 4.6",
			Provider:       "anthropic",
			Tier:           Tier1,
			ContextWindow:  1_000_000,
			MaxOutput:      16_000,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   3.0,
			PricingOutput:  15.0,
			Description:    "Balanced reasoning model with full agent capabilities",
			RecommendedFor: []string{"orchestrator", "sub_agent"},
		},
		"gpt-5.4": {
			ID:             "gpt-5.4",
			DisplayName:    "GPT-5.4",
			Provider:       "openai",
			Tier:           Tier1,
			ContextWindow:  272_000,
			MaxOutput:      16_384,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   2.5,
			PricingOutput:  15.0,
			Description:    "OpenAI flagship model with strong tool calling",
			RecommendedFor: []string{"orchestrator"},
		},
		"gpt-5.2": {
			ID:             "gpt-5.2",
			DisplayName:    "GPT-5.2",
			Provider:       "openai",
			Tier:           Tier1,
			ContextWindow:  200_000,
			MaxOutput:      16_384,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   1.75,
			PricingOutput:  14.0,
			Description:    "Previous-gen flagship, still highly capable",
			RecommendedFor: []string{"orchestrator"},
		},
		"gemini-3.1-pro": {
			ID:             "gemini-3.1-pro",
			DisplayName:    "Gemini 3.1 Pro",
			Provider:       "google",
			Tier:           Tier1,
			ContextWindow:  1_000_000,
			MaxOutput:      8_192,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   2.0,
			PricingOutput:  12.0,
			Description:    "Google flagship with million-token context",
			RecommendedFor: []string{"orchestrator"},
		},
		"grok-4.1": {
			ID:             "grok-4.1",
			DisplayName:    "Grok 4.1",
			Provider:       "xai",
			Tier:           Tier1,
			ContextWindow:  2_000_000,
			MaxOutput:      16_384,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   3.0,
			PricingOutput:  15.0,
			Description:    "xAI model with largest context window",
			RecommendedFor: []string{"orchestrator"},
		},
		"deepseek-chat": {
			ID:             "deepseek-chat",
			DisplayName:    "DeepSeek V3.2",
			Provider:       "deepseek",
			Tier:           Tier1,
			ContextWindow:  128_000,
			MaxOutput:      8_192,
			SupportsTools:  true,
			SupportsVision: false,
			PricingInput:   0.28,
			PricingOutput:  0.42,
			Description:    "Cost-effective model with strong coding capabilities",
			RecommendedFor: []string{"orchestrator", "sub_agent"},
		},
		"glm-5": {
			ID:             "glm-5",
			DisplayName:    "GLM-5",
			Provider:       "zai",
			Tier:           Tier1,
			ContextWindow:  200_000,
			MaxOutput:      8_192,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   1.0,
			PricingOutput:  3.2,
			Description:    "Z.ai flagship model with balanced pricing",
			RecommendedFor: []string{"orchestrator"},
		},

		// --- Tier 2: Sub-agent ---
		"gpt-5.4-mini": {
			ID:             "gpt-5.4-mini",
			DisplayName:    "GPT-5.4 Mini",
			Provider:       "openai",
			Tier:           Tier2,
			ContextWindow:  128_000,
			MaxOutput:      16_384,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   0.25,
			PricingOutput:  2.0,
			Description:    "Fast and affordable model for simple tool calling tasks",
			RecommendedFor: []string{"sub_agent"},
		},
		"claude-haiku-4-5": {
			ID:             "claude-haiku-4-5",
			DisplayName:    "Claude Haiku 4.5",
			Provider:       "anthropic",
			Tier:           Tier2,
			ContextWindow:  200_000,
			MaxOutput:      8_192,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   0.8,
			PricingOutput:  4.0,
			Description:    "Anthropic fast model for sub-agent tasks",
			RecommendedFor: []string{"sub_agent"},
		},
		"gemini-2.5-flash": {
			ID:             "gemini-2.5-flash",
			DisplayName:    "Gemini 2.5 Flash",
			Provider:       "google",
			Tier:           Tier2,
			ContextWindow:  1_000_000,
			MaxOutput:      8_192,
			SupportsTools:  true,
			SupportsVision: true,
			PricingInput:   0.3,
			PricingOutput:  2.5,
			Description:    "Google fast model with large context window",
			RecommendedFor: []string{"sub_agent"},
		},
		"glm-4.7": {
			ID:             "glm-4.7",
			DisplayName:    "GLM-4.7",
			Provider:       "zai",
			Tier:           Tier2,
			ContextWindow:  128_000,
			MaxOutput:      4_096,
			SupportsTools:  true,
			SupportsVision: false,
			PricingInput:   0.6,
			PricingOutput:  2.2,
			Description:    "Z.ai balanced sub-agent model",
			RecommendedFor: []string{"sub_agent"},
		},
		"mistral-medium-3": {
			ID:             "mistral-medium-3",
			DisplayName:    "Mistral Medium 3",
			Provider:       "mistral",
			Tier:           Tier2,
			ContextWindow:  128_000,
			MaxOutput:      8_192,
			SupportsTools:  true,
			SupportsVision: false,
			PricingInput:   0.4,
			PricingOutput:  2.0,
			Description:    "Mistral mid-range model for tool-calling tasks",
			RecommendedFor: []string{"sub_agent"},
		},

		// --- Tier 3: Utility ---
		"gpt-5.4-nano": {
			ID:             "gpt-5.4-nano",
			DisplayName:    "GPT-5.4 Nano",
			Provider:       "openai",
			Tier:           Tier3,
			ContextWindow:  128_000,
			MaxOutput:      4_096,
			SupportsTools:  false,
			SupportsVision: false,
			PricingInput:   0.05,
			PricingOutput:  0.4,
			Description:    "Ultra-cheap model for classification and simple tasks",
			RecommendedFor: []string{"utility"},
		},
	}
}
