// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, tier, status, proxy_steps_limit, byok_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, tier, status, current_period_start, current_period_end,
          stripe_subscription_id, proxy_steps_used, proxy_steps_limit, byok_enabled,
          created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Tier            string      `json:"tier"`
	Status          string      `json:"status"`
	ProxyStepsLimit int32       `json:"proxy_steps_limit"`
	ByokEnabled     bool        `json:"byok_enabled"`
}

type CreateSubscriptionRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Tier                 string             `json:"tier"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	ProxyStepsUsed       int32              `json:"proxy_steps_used"`
	ProxyStepsLimit      int32              `json:"proxy_steps_limit"`
	ByokEnabled          bool               `json:"byok_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.Tier,
		arg.Status,
		arg.ProxyStepsLimit,
		arg.ByokEnabled,
	)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.StripeSubscriptionID,
		&i.ProxyStepsUsed,
		&i.ProxyStepsLimit,
		&i.ByokEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, tier, status, current_period_start, current_period_end,
       stripe_subscription_id, proxy_steps_used, proxy_steps_limit, byok_enabled,
       created_at, updated_at
FROM subscriptions
WHERE user_id = $1
`

type GetSubscriptionByUserIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Tier                 string             `json:"tier"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	ProxyStepsUsed       int32              `json:"proxy_steps_used"`
	ProxyStepsLimit      int32              `json:"proxy_steps_limit"`
	ByokEnabled          bool               `json:"byok_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i GetSubscriptionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.StripeSubscriptionID,
		&i.ProxyStepsUsed,
		&i.ProxyStepsLimit,
		&i.ByokEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementProxySteps = `-- name: IncrementProxySteps :exec
UPDATE subscriptions SET proxy_steps_used = proxy_steps_used + 1, updated_at = NOW() WHERE user_id = $1
`

func (q *Queries) IncrementProxySteps(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementProxySteps, userID)
	return err
}

const resetProxyStepsUsed = `-- name: ResetProxyStepsUsed :exec
UPDATE subscriptions SET proxy_steps_used = 0, updated_at = NOW() WHERE user_id = $1
`

func (q *Queries) ResetProxyStepsUsed(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetProxyStepsUsed, userID)
	return err
}

const updateStripeSubscriptionID = `-- name: UpdateStripeSubscriptionID :exec
UPDATE subscriptions SET stripe_subscription_id = $1, updated_at = NOW() WHERE user_id = $2
`

type UpdateStripeSubscriptionIDParams struct {
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
	UserID               pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateStripeSubscriptionID(ctx context.Context, arg UpdateStripeSubscriptionIDParams) error {
	_, err := q.db.Exec(ctx, updateStripeSubscriptionID, arg.StripeSubscriptionID, arg.UserID)
	return err
}

const updateSubscriptionFull = `-- name: UpdateSubscriptionFull :exec
UPDATE subscriptions SET tier = $1, status = $2, current_period_start = $3,
  current_period_end = $4, stripe_subscription_id = $5, proxy_steps_limit = $6,
  updated_at = NOW()
WHERE user_id = $7
`

type UpdateSubscriptionFullParams struct {
	Tier                 string             `json:"tier"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	ProxyStepsLimit      int32              `json:"proxy_steps_limit"`
	UserID               pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateSubscriptionFull(ctx context.Context, arg UpdateSubscriptionFullParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionFull,
		arg.Tier,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.StripeSubscriptionID,
		arg.ProxyStepsLimit,
		arg.UserID,
	)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions SET status = $1, updated_at = NOW() WHERE user_id = $2
`

type UpdateSubscriptionStatusParams struct {
	Status string      `json:"status"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.Status, arg.UserID)
	return err
}

const updateSubscriptionTier = `-- name: UpdateSubscriptionTier :exec
UPDATE subscriptions
SET tier = $1, status = $2, current_period_start = $3,
    current_period_end = $4, updated_at = NOW()
WHERE user_id = $5
`

type UpdateSubscriptionTierParams struct {
	Tier               string             `json:"tier"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	UserID             pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateSubscriptionTier(ctx context.Context, arg UpdateSubscriptionTierParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionTier,
		arg.Tier,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.UserID,
	)
	return err
}
