// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: indexing_service.proto

package bytebrewv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexingService_IndexCodebase_FullMethodName = "/bytebrew.v1.IndexingService/IndexCodebase"
)

// IndexingServiceClient is the client API for IndexingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IndexingService handles code indexing from client to server
// Note: Indexing happens on CLIENT side, server only stores metadata
type IndexingServiceClient interface {
	// IndexCodebase receives code chunks and metadata from client
	IndexCodebase(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IndexCodebaseRequest, IndexCodebaseResponse], error)
}

type indexingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexingServiceClient(cc grpc.ClientConnInterface) IndexingServiceClient {
	return &indexingServiceClient{cc}
}

func (c *indexingServiceClient) IndexCodebase(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IndexCodebaseRequest, IndexCodebaseResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IndexingService_ServiceDesc.Streams[0], IndexingService_IndexCodebase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexCodebaseRequest, IndexCodebaseResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexingService_IndexCodebaseClient = grpc.BidiStreamingClient[IndexCodebaseRequest, IndexCodebaseResponse]

// IndexingServiceServer is the server API for IndexingService service.
// All implementations must embed UnimplementedIndexingServiceServer
// for forward compatibility.
//
// IndexingService handles code indexing from client to server
// Note: Indexing happens on CLIENT side, server only stores metadata
type IndexingServiceServer interface {
	// IndexCodebase receives code chunks and metadata from client
	IndexCodebase(grpc.BidiStreamingServer[IndexCodebaseRequest, IndexCodebaseResponse]) error
	mustEmbedUnimplementedIndexingServiceServer()
}

// UnimplementedIndexingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexingServiceServer struct{}

func (UnimplementedIndexingServiceServer) IndexCodebase(grpc.BidiStreamingServer[IndexCodebaseRequest, IndexCodebaseResponse]) error {
	return status.Error(codes.Unimplemented, "method IndexCodebase not implemented")
}
func (UnimplementedIndexingServiceServer) mustEmbedUnimplementedIndexingServiceServer() {}
func (UnimplementedIndexingServiceServer) testEmbeddedByValue()                         {}

// UnsafeIndexingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexingServiceServer will
// result in compilation errors.
type UnsafeIndexingServiceServer interface {
	mustEmbedUnimplementedIndexingServiceServer()
}

func RegisterIndexingServiceServer(s grpc.ServiceRegistrar, srv IndexingServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexingService_ServiceDesc, srv)
}

func _IndexingService_IndexCodebase_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexingServiceServer).IndexCodebase(&grpc.GenericServerStream[IndexCodebaseRequest, IndexCodebaseResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexingService_IndexCodebaseServer = grpc.BidiStreamingServer[IndexCodebaseRequest, IndexCodebaseResponse]

// IndexingService_ServiceDesc is the grpc.ServiceDesc for IndexingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bytebrew.v1.IndexingService",
	HandlerType: (*IndexingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IndexCodebase",
			Handler:       _IndexingService_IndexCodebase_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "indexing_service.proto",
}
