package domain

import (
	"fmt"
	"time"
)

// AgentState represents the state of an AI agent during execution
type AgentState struct {
	ID          string
	SessionID   string
	TaskID      string
	CurrentStep string
	Reasoning   string
	NextAction  string
	Observation string
	ToolCalls   []string // IDs of tool calls
	IsComplete  bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewAgentState creates a new AgentState with validation
func NewAgentState(sessionID, taskID string) (*AgentState, error) {
	state := &AgentState{
		ID:         "", // Will be generated by repository
		SessionID:  sessionID,
		TaskID:     taskID,
		ToolCalls:  make([]string, 0),
		IsComplete: false,
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
	}

	if err := state.Validate(); err != nil {
		return nil, err
	}

	return state, nil
}

// Validate validates the AgentState
func (as *AgentState) Validate() error {
	if as.SessionID == "" {
		return fmt.Errorf("session_id is required")
	}
	if as.TaskID == "" {
		return fmt.Errorf("task_id is required")
	}
	return nil
}

// UpdateStep updates the current step of the agent
func (as *AgentState) UpdateStep(step, reasoning, nextAction string) {
	as.CurrentStep = step
	as.Reasoning = reasoning
	as.NextAction = nextAction
	as.UpdatedAt = time.Now()
}

// AddObservation adds an observation from tool execution
func (as *AgentState) AddObservation(observation string) {
	as.Observation = observation
	as.UpdatedAt = time.Now()
}

// AddToolCall adds a tool call ID to the agent state
func (as *AgentState) AddToolCall(toolCallID string) {
	if as.ToolCalls == nil {
		as.ToolCalls = make([]string, 0)
	}
	as.ToolCalls = append(as.ToolCalls, toolCallID)
	as.UpdatedAt = time.Now()
}

// MarkComplete marks the agent execution as complete
func (as *AgentState) MarkComplete() {
	as.IsComplete = true
	as.UpdatedAt = time.Now()
}

// ToolCallCount returns the number of tool calls made
func (as *AgentState) ToolCallCount() int {
	return len(as.ToolCalls)
}
