package domain

import (
	"fmt"
	"time"
)

// MessageType represents the type of message
type MessageType string

const (
	MessageTypeUser   MessageType = "user"
	MessageTypeAgent  MessageType = "agent"
	MessageTypeSystem MessageType = "system"
	MessageTypeTool   MessageType = "tool" // Tool result message
)

// ToolCallInfo represents a tool call made by the assistant
type ToolCallInfo struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Arguments map[string]string `json:"arguments"`
}

// Message represents a message in a conversation
type Message struct {
	ID         string
	SessionID  string
	Type       MessageType
	Sender     string
	Content    string
	Metadata   map[string]string
	ToolCalls  []ToolCallInfo // For assistant messages with tool calls
	ToolCallID string         // For tool result messages - references the ToolCallInfo.ID
	ToolName   string         // For tool result messages - the name of the tool
	AgentID    string         // "supervisor" | "code-agent-{uuid}", empty for legacy messages
	CreatedAt  time.Time
}

// NewMessage creates a new Message with validation
func NewMessage(sessionID string, msgType MessageType, sender, content string) (*Message, error) {
	msg := &Message{
		ID:        "", // Will be generated by repository
		SessionID: sessionID,
		Type:      msgType,
		Sender:    sender,
		Content:   content,
		Metadata:  make(map[string]string),
		CreatedAt: time.Now(),
	}

	if err := msg.Validate(); err != nil {
		return nil, err
	}

	return msg, nil
}

// Validate validates the Message
func (m *Message) Validate() error {
	if m.SessionID == "" {
		return fmt.Errorf("session_id is required")
	}
	if m.Type == "" {
		return fmt.Errorf("message type is required")
	}
	if m.Sender == "" {
		return fmt.Errorf("sender is required")
	}

	// Validate message type
	switch m.Type {
	case MessageTypeUser, MessageTypeAgent, MessageTypeSystem:
		// Valid types - content required
		if m.Content == "" {
			return fmt.Errorf("content is required")
		}
	case MessageTypeTool:
		// Tool messages require ToolCallID
		if m.ToolCallID == "" {
			return fmt.Errorf("tool_call_id is required for tool messages")
		}
		// Content can be empty for tool results (e.g., empty result)
	default:
		return fmt.Errorf("invalid message type: %s", m.Type)
	}

	return nil
}

// AddMetadata adds metadata to the message
func (m *Message) AddMetadata(key, value string) {
	if m.Metadata == nil {
		m.Metadata = make(map[string]string)
	}
	m.Metadata[key] = value
}

// GetMetadata retrieves metadata from the message
func (m *Message) GetMetadata(key string) (string, bool) {
	if m.Metadata == nil {
		return "", false
	}
	value, ok := m.Metadata[key]
	return value, ok
}

// HistoryMessage represents a simplified message for conversation history
// Used to pass history between layers without full Message overhead
type HistoryMessage struct {
	Role       string         // "user", "assistant", or "tool"
	Content    string         // Message content
	ToolCalls  []ToolCallInfo // For assistant messages with tool calls
	ToolCallID string         // For tool messages - references the ToolCallInfo.ID
	ToolName   string         // For tool messages - the name of the tool
	AgentID    string         // Agent that produced this message
}

// ToHistoryMessage converts a Message to HistoryMessage
func (m *Message) ToHistoryMessage() HistoryMessage {
	hm := HistoryMessage{
		Content:    m.Content,
		ToolCalls:  m.ToolCalls,
		ToolCallID: m.ToolCallID,
		ToolName:   m.ToolName,
		AgentID:    m.AgentID,
	}

	switch m.Type {
	case MessageTypeUser:
		hm.Role = "user"
	case MessageTypeAgent:
		hm.Role = "assistant"
	case MessageTypeTool:
		hm.Role = "tool"
	case MessageTypeSystem:
		hm.Role = "system"
	default:
		hm.Role = "user"
	}

	return hm
}

// NewToolMessage creates a new tool result message
func NewToolMessage(sessionID, toolCallID, toolName, content string) (*Message, error) {
	msg := &Message{
		ID:         "",
		SessionID:  sessionID,
		Type:       MessageTypeTool,
		Sender:     toolName,
		Content:    content,
		ToolCallID: toolCallID,
		ToolName:   toolName,
		Metadata:   make(map[string]string),
		CreatedAt:  time.Now(),
	}

	if err := msg.Validate(); err != nil {
		return nil, err
	}

	return msg, nil
}

// NewAssistantMessageWithToolCalls creates a new assistant message with tool calls
func NewAssistantMessageWithToolCalls(sessionID, content string, toolCalls []ToolCallInfo) (*Message, error) {
	msg := &Message{
		ID:        "",
		SessionID: sessionID,
		Type:      MessageTypeAgent,
		Sender:    "assistant",
		Content:   content,
		ToolCalls: toolCalls,
		Metadata:  make(map[string]string),
		CreatedAt: time.Now(),
	}

	// For assistant messages with tool calls, content can be empty
	// Skip standard validation and do custom validation
	if msg.SessionID == "" {
		return nil, fmt.Errorf("session_id is required")
	}
	if len(msg.ToolCalls) == 0 && msg.Content == "" {
		return nil, fmt.Errorf("either content or tool_calls is required")
	}

	return msg, nil
}
