package domain

import (
	"fmt"
	"time"
)

// Project represents a user's codebase project
type Project struct {
	ID         string
	UserID     string
	Name       string
	RootPath   string
	ProjectKey string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// NewProject creates a new Project with validation
func NewProject(userID, name, rootPath, projectKey string) (*Project, error) {
	project := &Project{
		ID:         "", // Will be generated by repository
		UserID:     userID,
		Name:       name,
		RootPath:   rootPath,
		ProjectKey: projectKey,
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
	}

	if err := project.Validate(); err != nil {
		return nil, err
	}

	return project, nil
}

// Validate validates the Project entity
func (p *Project) Validate() error {
	if p.UserID == "" {
		return fmt.Errorf("user_id is required")
	}
	if p.Name == "" {
		return fmt.Errorf("name is required")
	}
	if len(p.Name) > 255 {
		return fmt.Errorf("name must not exceed 255 characters")
	}
	if p.RootPath == "" {
		return fmt.Errorf("root_path is required")
	}
	if len(p.RootPath) > 500 {
		return fmt.Errorf("root_path must not exceed 500 characters")
	}
	if p.ProjectKey == "" {
		return fmt.Errorf("project_key is required")
	}
	if len(p.ProjectKey) > 255 {
		return fmt.Errorf("project_key must not exceed 255 characters")
	}

	return nil
}

// UpdateName updates the project name
func (p *Project) UpdateName(newName string) error {
	if newName == "" {
		return fmt.Errorf("name cannot be empty")
	}
	if len(newName) > 255 {
		return fmt.Errorf("name must not exceed 255 characters")
	}
	p.Name = newName
	p.UpdatedAt = time.Now()
	return nil
}

// UpdateRootPath updates the project root path
func (p *Project) UpdateRootPath(newRootPath string) error {
	if newRootPath == "" {
		return fmt.Errorf("root_path cannot be empty")
	}
	if len(newRootPath) > 500 {
		return fmt.Errorf("root_path must not exceed 500 characters")
	}
	p.RootPath = newRootPath
	p.UpdatedAt = time.Now()
	return nil
}
