package domain

import (
	"fmt"
	"time"
)

// ProjectFile represents file metadata with AI-generated description
type ProjectFile struct {
	ID          string
	ProjectID   string
	FilePath    string
	Description string
	Language    string
	SizeBytes   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewProjectFile creates a new ProjectFile with validation
func NewProjectFile(projectID, filePath, description, language string, sizeBytes int64) (*ProjectFile, error) {
	file := &ProjectFile{
		ID:          "", // Will be generated by repository
		ProjectID:   projectID,
		FilePath:    filePath,
		Description: description,
		Language:    language,
		SizeBytes:   sizeBytes,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	if err := file.Validate(); err != nil {
		return nil, err
	}

	return file, nil
}

// Validate validates the ProjectFile entity
func (pf *ProjectFile) Validate() error {
	if pf.ProjectID == "" {
		return fmt.Errorf("project_id is required")
	}
	if pf.FilePath == "" {
		return fmt.Errorf("file_path is required")
	}
	if len(pf.FilePath) > 500 {
		return fmt.Errorf("file_path must not exceed 500 characters")
	}
	if pf.Description == "" {
		return fmt.Errorf("description is required")
	}
	if pf.Language == "" {
		return fmt.Errorf("language is required")
	}
	if len(pf.Language) > 50 {
		return fmt.Errorf("language must not exceed 50 characters")
	}
	if pf.SizeBytes < 0 {
		return fmt.Errorf("size_bytes must be non-negative")
	}

	return nil
}

// UpdateDescription updates the file description
func (pf *ProjectFile) UpdateDescription(newDescription string) error {
	if newDescription == "" {
		return fmt.Errorf("description cannot be empty")
	}
	pf.Description = newDescription
	pf.UpdatedAt = time.Now()
	return nil
}

// UpdateLanguage updates the file language
func (pf *ProjectFile) UpdateLanguage(newLanguage string) error {
	if newLanguage == "" {
		return fmt.Errorf("language cannot be empty")
	}
	if len(newLanguage) > 50 {
		return fmt.Errorf("language must not exceed 50 characters")
	}
	pf.Language = newLanguage
	pf.UpdatedAt = time.Now()
	return nil
}
