package domain

import (
	"fmt"
	"time"
)

// SubtaskStatus represents the status of a subtask
type SubtaskStatus string

const (
	SubtaskStatusPending         SubtaskStatus = "pending"
	SubtaskStatusInProgress      SubtaskStatus = "in_progress"
	SubtaskStatusWaitingForInput SubtaskStatus = "waiting_for_input"
	SubtaskStatusCompleted       SubtaskStatus = "completed"
	SubtaskStatusFailed          SubtaskStatus = "failed"
	SubtaskStatusCancelled       SubtaskStatus = "cancelled"
)

// Subtask represents a subtask for a Code Agent
type Subtask struct {
	ID              string
	SessionID       string
	TaskID          string            // FK to Task.ID (empty for standalone subtasks)
	Title           string            // Short title for the subtask
	Description     string            // Detailed description
	Status          SubtaskStatus
	AssignedAgentID string            // Which Code Agent is executing this
	BlockedBy       []string          // Subtask IDs that block this subtask
	FilesInvolved   []string          // Files that this subtask touches
	Context         map[string]string
	Result          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CompletedAt     *time.Time
}

// NewSubtask creates a new Subtask with validation (legacy constructor for standalone subtasks)
func NewSubtask(sessionID, description string) (*Subtask, error) {
	subtask := &Subtask{
		ID:          "", // Will be generated by repository
		SessionID:   sessionID,
		Description: description,
		Status:      SubtaskStatusPending,
		Context:     make(map[string]string),
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	if err := subtask.Validate(); err != nil {
		return nil, err
	}

	return subtask, nil
}

// NewTaskSubtask creates a new Subtask associated with a Task
func NewTaskSubtask(id, sessionID, taskID, title, description string, blockedBy, files []string) (*Subtask, error) {
	now := time.Now()
	subtask := &Subtask{
		ID:            id,
		SessionID:     sessionID,
		TaskID:        taskID,
		Title:         title,
		Description:   description,
		Status:        SubtaskStatusPending,
		BlockedBy:     blockedBy,
		FilesInvolved: files,
		Context:       make(map[string]string),
		CreatedAt:     now,
		UpdatedAt:     now,
	}

	if err := subtask.Validate(); err != nil {
		return nil, err
	}

	return subtask, nil
}

// Validate validates the Subtask
func (s *Subtask) Validate() error {
	if s.SessionID == "" {
		return fmt.Errorf("session_id is required")
	}
	if s.Description == "" && s.Title == "" {
		return fmt.Errorf("title or description is required")
	}

	// Validate status
	switch s.Status {
	case SubtaskStatusPending, SubtaskStatusInProgress, SubtaskStatusWaitingForInput,
		SubtaskStatusCompleted, SubtaskStatusFailed, SubtaskStatusCancelled:
		// Valid statuses
	default:
		return fmt.Errorf("invalid subtask status: %s", s.Status)
	}

	return nil
}

// Start marks the subtask as in progress
func (s *Subtask) Start() error {
	if s.Status != SubtaskStatusPending {
		return fmt.Errorf("subtask must be pending to start")
	}
	s.Status = SubtaskStatusInProgress
	s.UpdatedAt = time.Now()
	return nil
}

// Complete marks the subtask as completed with a result
func (s *Subtask) Complete(result string) error {
	if s.Status != SubtaskStatusInProgress {
		return fmt.Errorf("subtask must be in progress to complete")
	}
	s.Status = SubtaskStatusCompleted
	s.Result = result
	now := time.Now()
	s.CompletedAt = &now
	s.UpdatedAt = now
	return nil
}

// Fail marks the subtask as failed with a reason
func (s *Subtask) Fail(reason string) error {
	if s.Status != SubtaskStatusInProgress {
		return fmt.Errorf("subtask must be in progress to fail")
	}
	s.Status = SubtaskStatusFailed
	s.Result = reason
	s.UpdatedAt = time.Now()
	return nil
}

// Cancel marks the subtask as cancelled
func (s *Subtask) Cancel() error {
	if s.Status == SubtaskStatusCompleted {
		return fmt.Errorf("cannot cancel completed subtask")
	}
	s.Status = SubtaskStatusCancelled
	s.UpdatedAt = time.Now()
	return nil
}

// WaitForInput marks the subtask as waiting for user input
func (s *Subtask) WaitForInput() error {
	if s.Status != SubtaskStatusInProgress {
		return fmt.Errorf("subtask must be in progress to wait for input")
	}
	s.Status = SubtaskStatusWaitingForInput
	s.UpdatedAt = time.Now()
	return nil
}

// Resume resumes a subtask that was waiting for input
func (s *Subtask) Resume() error {
	if s.Status != SubtaskStatusWaitingForInput {
		return fmt.Errorf("subtask must be waiting for input to resume")
	}
	s.Status = SubtaskStatusInProgress
	s.UpdatedAt = time.Now()
	return nil
}

// AssignToAgent assigns this subtask to a Code Agent
func (s *Subtask) AssignToAgent(agentID string) {
	s.AssignedAgentID = agentID
	s.UpdatedAt = time.Now()
}

// IsBlocked returns true if any blocking subtasks exist
func (s *Subtask) IsBlocked() bool {
	return len(s.BlockedBy) > 0
}

// AddContext adds context information to the subtask
func (s *Subtask) AddContext(key, value string) {
	if s.Context == nil {
		s.Context = make(map[string]string)
	}
	s.Context[key] = value
	s.UpdatedAt = time.Now()
}

// IsCompleted returns true if the subtask is completed
func (s *Subtask) IsCompleted() bool {
	return s.Status == SubtaskStatusCompleted
}

// IsCancelled returns true if the subtask is cancelled
func (s *Subtask) IsCancelled() bool {
	return s.Status == SubtaskStatusCancelled
}

// IsTerminal returns true if the subtask is in a terminal state
func (s *Subtask) IsTerminal() bool {
	return s.Status == SubtaskStatusCompleted ||
		s.Status == SubtaskStatusFailed ||
		s.Status == SubtaskStatusCancelled
}
