package domain

import (
	"fmt"
	"time"
)

// TaskArtifact represents structured results from agents
type TaskArtifact struct {
	ID             string
	TaskID         string
	ArtifactType   string
	Content        map[string]interface{}
	FilePath       string
	CreatedByAgent string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// NewTaskArtifact creates a new TaskArtifact with validation
func NewTaskArtifact(taskID, artifactType string, content map[string]interface{}, filePath, createdByAgent string) (*TaskArtifact, error) {
	artifact := &TaskArtifact{
		ID:             "", // Will be generated by repository
		TaskID:         taskID,
		ArtifactType:   artifactType,
		Content:        content,
		FilePath:       filePath,
		CreatedByAgent: createdByAgent,
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
	}

	if err := artifact.Validate(); err != nil {
		return nil, err
	}

	return artifact, nil
}

// Validate validates the TaskArtifact entity
func (ta *TaskArtifact) Validate() error {
	if ta.TaskID == "" {
		return fmt.Errorf("task_id is required")
	}
	if ta.ArtifactType == "" {
		return fmt.Errorf("artifact_type is required")
	}
	if len(ta.ArtifactType) > 100 {
		return fmt.Errorf("artifact_type must not exceed 100 characters")
	}
	if ta.Content == nil {
		return fmt.Errorf("content is required")
	}
	if ta.CreatedByAgent == "" {
		return fmt.Errorf("created_by_agent is required")
	}
	if len(ta.CreatedByAgent) > 100 {
		return fmt.Errorf("created_by_agent must not exceed 100 characters")
	}
	if len(ta.FilePath) > 500 {
		return fmt.Errorf("file_path must not exceed 500 characters")
	}

	return nil
}

// UpdateContent updates the artifact content
func (ta *TaskArtifact) UpdateContent(newContent map[string]interface{}) error {
	if newContent == nil {
		return fmt.Errorf("content cannot be nil")
	}
	ta.Content = newContent
	ta.UpdatedAt = time.Now()
	return nil
}

// AddContentField adds a field to the artifact content
func (ta *TaskArtifact) AddContentField(key string, value interface{}) {
	if ta.Content == nil {
		ta.Content = make(map[string]interface{})
	}
	ta.Content[key] = value
	ta.UpdatedAt = time.Now()
}

// GetContentField retrieves a field from the artifact content
func (ta *TaskArtifact) GetContentField(key string) (interface{}, bool) {
	if ta.Content == nil {
		return nil, false
	}
	value, ok := ta.Content[key]
	return value, ok
}
