// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPasswordResetToken = `-- name: ClearPasswordResetToken :exec
UPDATE users
SET password_reset_token = NULL, password_reset_expires_at = NULL
WHERE id = $1
`

func (q *Queries) ClearPasswordResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPasswordResetToken, id)
	return err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (email, password_hash, google_id, email_verified)
VALUES ($1, '', $2, true)
RETURNING id, email, password_hash, google_id, email_verified, created_at
`

type CreateGoogleUserParams struct {
	Email    string      `json:"email"`
	GoogleID pgtype.Text `json:"google_id"`
}

type CreateGoogleUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	GoogleID      pgtype.Text        `json:"google_id"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (CreateGoogleUserRow, error) {
	row := q.db.QueryRow(ctx, createGoogleUser, arg.Email, arg.GoogleID)
	var i CreateGoogleUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, email_verified, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreateUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, google_id, email_verified, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	GoogleID      pgtype.Text        `json:"google_id"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password_hash, google_id, email_verified, created_at
FROM users
WHERE google_id = $1
`

type GetUserByGoogleIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	GoogleID      pgtype.Text        `json:"google_id"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (GetUserByGoogleIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i GetUserByGoogleIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, email_verified, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, email, password_hash, created_at, password_reset_token, password_reset_expires_at
FROM users
WHERE password_reset_token = $1
  AND password_reset_expires_at > NOW()
`

type GetUserByResetTokenRow struct {
	ID                     pgtype.UUID        `json:"id"`
	Email                  string             `json:"email"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	PasswordResetToken     pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
}

func (q *Queries) GetUserByResetToken(ctx context.Context, passwordResetToken pgtype.Text) (GetUserByResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, passwordResetToken)
	var i GetUserByResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, password_hash, email_verified, created_at
FROM users
WHERE verification_token = $1
  AND verification_expires_at > NOW()
`

type GetUserByVerificationTokenRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (GetUserByVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i GetUserByVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :exec
UPDATE users SET google_id = $2 WHERE id = $1
`

type LinkGoogleIDParams struct {
	ID       pgtype.UUID `json:"id"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) error {
	_, err := q.db.Exec(ctx, linkGoogleID, arg.ID, arg.GoogleID)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users
SET email_verified = true, verification_token = NULL, verification_expires_at = NULL
WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users
SET password_reset_token = $2, password_reset_expires_at = $3
WHERE id = $1
`

type SetPasswordResetTokenParams struct {
	ID                     pgtype.UUID        `json:"id"`
	PasswordResetToken     pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.ID, arg.PasswordResetToken, arg.PasswordResetExpiresAt)
	return err
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users
SET verification_token = $2, verification_expires_at = $3
WHERE id = $1
`

type SetVerificationTokenParams struct {
	ID                    pgtype.UUID        `json:"id"`
	VerificationToken     pgtype.Text        `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setVerificationToken, arg.ID, arg.VerificationToken, arg.VerificationExpiresAt)
	return err
}

const updatePasswordAndClearResetToken = `-- name: UpdatePasswordAndClearResetToken :exec
UPDATE users
SET password_hash = $2, password_reset_token = NULL, password_reset_expires_at = NULL
WHERE id = $1
`

type UpdatePasswordAndClearResetTokenParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordAndClearResetToken(ctx context.Context, arg UpdatePasswordAndClearResetTokenParams) error {
	_, err := q.db.Exec(ctx, updatePasswordAndClearResetToken, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
