package domain

import (
	"fmt"
)

// AgentType represents predefined agent types
type AgentType struct {
	ID           string
	Code         string
	Name         string
	Description  string
	SystemPrompt string
	Tools        []string
}

// NewAgentType creates a new AgentType with validation
func NewAgentType(code, name, description, systemPrompt string, tools []string) (*AgentType, error) {
	agentType := &AgentType{
		ID:           "", // Will be generated by repository
		Code:         code,
		Name:         name,
		Description:  description,
		SystemPrompt: systemPrompt,
		Tools:        tools,
	}

	if err := agentType.Validate(); err != nil {
		return nil, err
	}

	return agentType, nil
}

// Validate validates the AgentType entity
func (at *AgentType) Validate() error {
	if at.Code == "" {
		return fmt.Errorf("code is required")
	}
	if len(at.Code) > 100 {
		return fmt.Errorf("code must not exceed 100 characters")
	}
	if at.Name == "" {
		return fmt.Errorf("name is required")
	}
	if len(at.Name) > 255 {
		return fmt.Errorf("name must not exceed 255 characters")
	}
	if at.SystemPrompt == "" {
		return fmt.Errorf("system_prompt is required")
	}

	return nil
}

// UpdateSystemPrompt updates the agent type system prompt
func (at *AgentType) UpdateSystemPrompt(newPrompt string) error {
	if newPrompt == "" {
		return fmt.Errorf("system_prompt cannot be empty")
	}
	at.SystemPrompt = newPrompt
	return nil
}

// AddTool adds a tool to the agent type
func (at *AgentType) AddTool(tool string) error {
	if tool == "" {
		return fmt.Errorf("tool cannot be empty")
	}

	for _, t := range at.Tools {
		if t == tool {
			return fmt.Errorf("tool already exists: %s", tool)
		}
	}

	at.Tools = append(at.Tools, tool)
	return nil
}

// RemoveTool removes a tool from the agent type
func (at *AgentType) RemoveTool(tool string) error {
	if tool == "" {
		return fmt.Errorf("tool cannot be empty")
	}

	for i, t := range at.Tools {
		if t == tool {
			at.Tools = append(at.Tools[:i], at.Tools[i+1:]...)
			return nil
		}
	}

	return fmt.Errorf("tool not found: %s", tool)
}

// HasTool checks if the agent type has a specific tool
func (at *AgentType) HasTool(tool string) bool {
	for _, t := range at.Tools {
		if t == tool {
			return true
		}
	}
	return false
}
