package domain

import (
	"fmt"
	"time"
)

// ChatSession represents a chat session aggregate root
type ChatSession struct {
	ID        string
	UserID    string
	ProjectID *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewChatSession creates a new ChatSession with validation
func NewChatSession(userID string, projectID *string) (*ChatSession, error) {
	session := &ChatSession{
		ID:        "", // Will be generated by repository
		UserID:    userID,
		ProjectID: projectID,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	if err := session.Validate(); err != nil {
		return nil, err
	}

	return session, nil
}

// Validate validates the ChatSession entity
func (cs *ChatSession) Validate() error {
	if cs.UserID == "" {
		return fmt.Errorf("user_id is required")
	}

	return nil
}

// AssignProject assigns a project to the chat session
func (cs *ChatSession) AssignProject(projectID string) error {
	if projectID == "" {
		return fmt.Errorf("project_id cannot be empty")
	}
	cs.ProjectID = &projectID
	cs.UpdatedAt = time.Now()
	return nil
}

// UnassignProject removes the project assignment from the chat session
func (cs *ChatSession) UnassignProject() {
	cs.ProjectID = nil
	cs.UpdatedAt = time.Now()
}

// HasProject returns true if the session has an assigned project
func (cs *ChatSession) HasProject() bool {
	return cs.ProjectID != nil
}
