package domain

import (
	"fmt"
	"time"
)

// MemoryLevel represents the level of memory persistence
type MemoryLevel string

const (
	MemoryLevelConversation MemoryLevel = "conversation"
	MemoryLevelSession      MemoryLevel = "session"
	MemoryLevelUser         MemoryLevel = "user"
)

// Memory represents a long-term memory entry
type Memory struct {
	ID        string
	UserID    string
	Content   string
	Level     MemoryLevel
	Metadata  map[string]string
	Embedding []float32
	IsValid   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewMemory creates a new Memory with validation
func NewMemory(userID, content string, level MemoryLevel) (*Memory, error) {
	mem := &Memory{
		ID:        "", // Will be generated by repository
		UserID:    userID,
		Content:   content,
		Level:     level,
		Metadata:  make(map[string]string),
		IsValid:   true,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	if err := mem.Validate(); err != nil {
		return nil, err
	}

	return mem, nil
}

// Validate validates the Memory
func (m *Memory) Validate() error {
	if m.UserID == "" {
		return fmt.Errorf("user_id is required")
	}
	if m.Content == "" {
		return fmt.Errorf("content is required")
	}

	// Validate memory level
	switch m.Level {
	case MemoryLevelConversation, MemoryLevelSession, MemoryLevelUser:
		// Valid levels
	default:
		return fmt.Errorf("invalid memory level: %s", m.Level)
	}

	return nil
}

// Invalidate marks the memory as invalid
func (m *Memory) Invalidate() {
	m.IsValid = false
	m.UpdatedAt = time.Now()
}

// SetEmbedding sets the embedding vector for the memory
func (m *Memory) SetEmbedding(embedding []float32) error {
	if len(embedding) == 0 {
		return fmt.Errorf("embedding cannot be empty")
	}
	m.Embedding = embedding
	m.UpdatedAt = time.Now()
	return nil
}

// AddMetadata adds metadata to the memory
func (m *Memory) AddMetadata(key, value string) {
	if m.Metadata == nil {
		m.Metadata = make(map[string]string)
	}
	m.Metadata[key] = value
	m.UpdatedAt = time.Now()
}

// GetMetadata retrieves metadata from the memory
func (m *Memory) GetMetadata(key string) (string, bool) {
	if m.Metadata == nil {
		return "", false
	}
	value, ok := m.Metadata[key]
	return value, ok
}
