package domain

import (
	"fmt"
	"regexp"
	"time"
)

// User represents a user account in the system
type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// NewUser creates a new User with validation
func NewUser(username, email, passwordHash string) (*User, error) {
	user := &User{
		ID:           "", // Will be generated by repository
		Username:     username,
		Email:        email,
		PasswordHash: passwordHash,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	if err := user.Validate(); err != nil {
		return nil, err
	}

	return user, nil
}

// Validate validates the User entity
func (u *User) Validate() error {
	if u.Username == "" {
		return fmt.Errorf("username is required")
	}
	if len(u.Username) < 3 || len(u.Username) > 255 {
		return fmt.Errorf("username must be between 3 and 255 characters")
	}
	if u.Email == "" {
		return fmt.Errorf("email is required")
	}
	if !isValidEmail(u.Email) {
		return fmt.Errorf("invalid email format")
	}
	if u.PasswordHash == "" {
		return fmt.Errorf("password hash is required")
	}

	return nil
}

// UpdatePassword updates the user's password hash
func (u *User) UpdatePassword(newPasswordHash string) error {
	if newPasswordHash == "" {
		return fmt.Errorf("password hash cannot be empty")
	}
	u.PasswordHash = newPasswordHash
	u.UpdatedAt = time.Now()
	return nil
}

// UpdateEmail updates the user's email
func (u *User) UpdateEmail(newEmail string) error {
	if newEmail == "" {
		return fmt.Errorf("email cannot be empty")
	}
	if !isValidEmail(newEmail) {
		return fmt.Errorf("invalid email format")
	}
	u.Email = newEmail
	u.UpdatedAt = time.Now()
	return nil
}

// isValidEmail validates email format
func isValidEmail(email string) bool {
	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)
	return emailRegex.MatchString(email)
}
