package domain

import (
	"fmt"
	"time"
)

// WorkflowStepStatus represents the status of a workflow step
type WorkflowStepStatus string

const (
	WorkflowStepStatusPending   WorkflowStepStatus = "pending"
	WorkflowStepStatusRunning   WorkflowStepStatus = "running"
	WorkflowStepStatusCompleted WorkflowStepStatus = "completed"
	WorkflowStepStatusFailed    WorkflowStepStatus = "failed"
	WorkflowStepStatusSkipped   WorkflowStepStatus = "skipped"
)

// WorkflowStep represents individual step in workflow execution
type WorkflowStep struct {
	ID          string
	WorkflowID  string
	StepNumber  int
	AgentTypeID string
	Status      WorkflowStepStatus
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewWorkflowStep creates a new WorkflowStep with validation
func NewWorkflowStep(workflowID string, stepNumber int, agentTypeID string) (*WorkflowStep, error) {
	step := &WorkflowStep{
		ID:          "", // Will be generated by repository
		WorkflowID:  workflowID,
		StepNumber:  stepNumber,
		AgentTypeID: agentTypeID,
		Status:      WorkflowStepStatusPending,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	if err := step.Validate(); err != nil {
		return nil, err
	}

	return step, nil
}

// Validate validates the WorkflowStep entity
func (ws *WorkflowStep) Validate() error {
	if ws.WorkflowID == "" {
		return fmt.Errorf("workflow_id is required")
	}
	if ws.StepNumber < 0 {
		return fmt.Errorf("step_number must be non-negative")
	}
	if ws.AgentTypeID == "" {
		return fmt.Errorf("agent_type_id is required")
	}

	switch ws.Status {
	case WorkflowStepStatusPending, WorkflowStepStatusRunning, WorkflowStepStatusCompleted,
		WorkflowStepStatusFailed, WorkflowStepStatusSkipped:
		// Valid statuses
	default:
		return fmt.Errorf("invalid workflow step status: %s", ws.Status)
	}

	return nil
}

// Start marks the step as running
func (ws *WorkflowStep) Start() error {
	if ws.Status != WorkflowStepStatusPending {
		return fmt.Errorf("step must be pending to start")
	}
	ws.Status = WorkflowStepStatusRunning
	ws.UpdatedAt = time.Now()
	return nil
}

// Complete marks the step as completed
func (ws *WorkflowStep) Complete() error {
	if ws.Status != WorkflowStepStatusRunning {
		return fmt.Errorf("step must be running to complete")
	}
	ws.Status = WorkflowStepStatusCompleted
	ws.UpdatedAt = time.Now()
	return nil
}

// Fail marks the step as failed
func (ws *WorkflowStep) Fail() error {
	if ws.Status == WorkflowStepStatusCompleted {
		return fmt.Errorf("cannot fail completed step")
	}
	ws.Status = WorkflowStepStatusFailed
	ws.UpdatedAt = time.Now()
	return nil
}

// Skip marks the step as skipped
func (ws *WorkflowStep) Skip() error {
	if ws.Status != WorkflowStepStatusPending {
		return fmt.Errorf("only pending steps can be skipped")
	}
	ws.Status = WorkflowStepStatusSkipped
	ws.UpdatedAt = time.Now()
	return nil
}

// IsCompleted returns true if the step is completed
func (ws *WorkflowStep) IsCompleted() bool {
	return ws.Status == WorkflowStepStatusCompleted
}

// IsFailed returns true if the step is failed
func (ws *WorkflowStep) IsFailed() bool {
	return ws.Status == WorkflowStepStatusFailed
}

// IsSkipped returns true if the step is skipped
func (ws *WorkflowStep) IsSkipped() bool {
	return ws.Status == WorkflowStepStatusSkipped
}
