package domain

import (
	"fmt"
	"time"
)

// ToolCallStatus represents the status of a tool call
type ToolCallStatus string

const (
	ToolCallStatusPending   ToolCallStatus = "pending"
	ToolCallStatusExecuting ToolCallStatus = "executing"
	ToolCallStatusCompleted ToolCallStatus = "completed"
	ToolCallStatusFailed    ToolCallStatus = "failed"
)

// ToolCall represents a tool invocation by an agent
type ToolCall struct {
	ID        string
	SessionID string
	ToolName  string
	Arguments map[string]string
	Status    ToolCallStatus
	Result    string
	Error     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewToolCall creates a new ToolCall with validation
func NewToolCall(sessionID, toolName string, arguments map[string]string) (*ToolCall, error) {
	tc := &ToolCall{
		ID:        "", // Will be generated by repository
		SessionID: sessionID,
		ToolName:  toolName,
		Arguments: arguments,
		Status:    ToolCallStatusPending,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	if err := tc.Validate(); err != nil {
		return nil, err
	}

	return tc, nil
}

// Validate validates the ToolCall
func (tc *ToolCall) Validate() error {
	if tc.SessionID == "" {
		return fmt.Errorf("session_id is required")
	}
	if tc.ToolName == "" {
		return fmt.Errorf("tool_name is required")
	}

	// Validate status
	switch tc.Status {
	case ToolCallStatusPending, ToolCallStatusExecuting,
		ToolCallStatusCompleted, ToolCallStatusFailed:
		// Valid statuses
	default:
		return fmt.Errorf("invalid tool call status: %s", tc.Status)
	}

	return nil
}

// Execute marks the tool call as executing
func (tc *ToolCall) Execute() error {
	if tc.Status != ToolCallStatusPending {
		return fmt.Errorf("tool call must be pending to execute")
	}
	tc.Status = ToolCallStatusExecuting
	tc.UpdatedAt = time.Now()
	return nil
}

// Complete marks the tool call as completed with a result
func (tc *ToolCall) Complete(result string) error {
	if tc.Status != ToolCallStatusExecuting {
		return fmt.Errorf("tool call must be executing to complete")
	}
	tc.Status = ToolCallStatusCompleted
	tc.Result = result
	tc.UpdatedAt = time.Now()
	return nil
}

// Fail marks the tool call as failed with an error
func (tc *ToolCall) Fail(errMsg string) error {
	if tc.Status != ToolCallStatusExecuting {
		return fmt.Errorf("tool call must be executing to fail")
	}
	tc.Status = ToolCallStatusFailed
	tc.Error = errMsg
	tc.UpdatedAt = time.Now()
	return nil
}

// IsCompleted returns true if the tool call is completed
func (tc *ToolCall) IsCompleted() bool {
	return tc.Status == ToolCallStatusCompleted
}

// IsFailed returns true if the tool call failed
func (tc *ToolCall) IsFailed() bool {
	return tc.Status == ToolCallStatusFailed
}

// GetArgument retrieves an argument by key
func (tc *ToolCall) GetArgument(key string) (string, bool) {
	if tc.Arguments == nil {
		return "", false
	}
	value, ok := tc.Arguments[key]
	return value, ok
}
