package domain

import (
	"fmt"
	"time"
)

// WorkflowStatus represents the status of a workflow execution
type WorkflowStatus string

const (
	WorkflowStatusPending   WorkflowStatus = "pending"
	WorkflowStatusRunning   WorkflowStatus = "running"
	WorkflowStatusCompleted WorkflowStatus = "completed"
	WorkflowStatusFailed    WorkflowStatus = "failed"
	WorkflowStatusCancelled WorkflowStatus = "cancelled"
)

// WorkflowExecution represents execution instance of workflow
type WorkflowExecution struct {
	ID           string
	TaskID       string
	WorkflowType string
	Status       WorkflowStatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// NewWorkflowExecution creates a new WorkflowExecution with validation
func NewWorkflowExecution(taskID, workflowType string) (*WorkflowExecution, error) {
	execution := &WorkflowExecution{
		ID:           "", // Will be generated by repository
		TaskID:       taskID,
		WorkflowType: workflowType,
		Status:       WorkflowStatusPending,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	if err := execution.Validate(); err != nil {
		return nil, err
	}

	return execution, nil
}

// Validate validates the WorkflowExecution entity
func (we *WorkflowExecution) Validate() error {
	if we.TaskID == "" {
		return fmt.Errorf("task_id is required")
	}
	if we.WorkflowType == "" {
		return fmt.Errorf("workflow_type is required")
	}
	if len(we.WorkflowType) > 100 {
		return fmt.Errorf("workflow_type must not exceed 100 characters")
	}

	switch we.Status {
	case WorkflowStatusPending, WorkflowStatusRunning, WorkflowStatusCompleted,
		WorkflowStatusFailed, WorkflowStatusCancelled:
		// Valid statuses
	default:
		return fmt.Errorf("invalid workflow status: %s", we.Status)
	}

	return nil
}

// Start marks the workflow as running
func (we *WorkflowExecution) Start() error {
	if we.Status != WorkflowStatusPending {
		return fmt.Errorf("workflow must be pending to start")
	}
	we.Status = WorkflowStatusRunning
	we.UpdatedAt = time.Now()
	return nil
}

// Complete marks the workflow as completed
func (we *WorkflowExecution) Complete() error {
	if we.Status != WorkflowStatusRunning {
		return fmt.Errorf("workflow must be running to complete")
	}
	we.Status = WorkflowStatusCompleted
	we.UpdatedAt = time.Now()
	return nil
}

// Fail marks the workflow as failed
func (we *WorkflowExecution) Fail() error {
	if we.Status == WorkflowStatusCompleted {
		return fmt.Errorf("cannot fail completed workflow")
	}
	we.Status = WorkflowStatusFailed
	we.UpdatedAt = time.Now()
	return nil
}

// Cancel marks the workflow as cancelled
func (we *WorkflowExecution) Cancel() error {
	if we.Status == WorkflowStatusCompleted {
		return fmt.Errorf("cannot cancel completed workflow")
	}
	we.Status = WorkflowStatusCancelled
	we.UpdatedAt = time.Now()
	return nil
}

// IsCompleted returns true if the workflow is completed
func (we *WorkflowExecution) IsCompleted() bool {
	return we.Status == WorkflowStatusCompleted
}

// IsFailed returns true if the workflow is failed
func (we *WorkflowExecution) IsFailed() bool {
	return we.Status == WorkflowStatusFailed
}

// IsCancelled returns true if the workflow is cancelled
func (we *WorkflowExecution) IsCancelled() bool {
	return we.Status == WorkflowStatusCancelled
}
