// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedStripeEvent struct {
	EventID     string             `json:"event_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type StripeCustomer struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CustomerID string             `json:"customer_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Tier                 string             `json:"tier"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ProxyStepsUsed       int32              `json:"proxy_steps_used"`
	ProxyStepsLimit      int32              `json:"proxy_steps_limit"`
	ByokEnabled          bool               `json:"byok_enabled"`
}

type Team struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	MaxSeats  int32              `json:"max_seats"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeamInvite struct {
	ID        pgtype.UUID        `json:"id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	Email     string             `json:"email"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	Token     string             `json:"token"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type TeamMember struct {
	ID       pgtype.UUID        `json:"id"`
	TeamID   pgtype.UUID        `json:"team_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID                     pgtype.UUID        `json:"id"`
	Email                  string             `json:"email"`
	PasswordHash           string             `json:"password_hash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	PasswordResetToken     pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
}
