// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	ClearPasswordResetToken(ctx context.Context, id pgtype.UUID) error
	CountTeamMembers(ctx context.Context, teamID pgtype.UUID) (int64, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamInvite(ctx context.Context, arg CreateTeamInviteParams) (TeamInvite, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUserByID(ctx context.Context, id pgtype.UUID) error
	GetStripeCustomerByUserID(ctx context.Context, userID pgtype.UUID) (StripeCustomer, error)
	GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetSubscriptionByUserIDRow, error)
	GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error)
	GetTeamByOwnerID(ctx context.Context, ownerID pgtype.UUID) (Team, error)
	GetTeamByUserID(ctx context.Context, userID pgtype.UUID) (Team, error)
	GetTeamInviteByToken(ctx context.Context, token string) (TeamInvite, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByResetToken(ctx context.Context, passwordResetToken pgtype.Text) (User, error)
	GetUserIDByStripeCustomerID(ctx context.Context, customerID string) (pgtype.UUID, error)
	IncrementProxySteps(ctx context.Context, userID pgtype.UUID) error
	InsertProcessedEvent(ctx context.Context, arg InsertProcessedEventParams) error
	IsEventProcessed(ctx context.Context, eventID string) (bool, error)
	ListPendingInvites(ctx context.Context, teamID pgtype.UUID) ([]TeamInvite, error)
	ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ResetProxyStepsUsed(ctx context.Context, userID pgtype.UUID) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) error
	UpdatePasswordAndClearResetToken(ctx context.Context, arg UpdatePasswordAndClearResetTokenParams) error
	UpdateStripeSubscriptionID(ctx context.Context, arg UpdateStripeSubscriptionIDParams) error
	UpdateSubscriptionFull(ctx context.Context, arg UpdateSubscriptionFullParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateSubscriptionTier(ctx context.Context, arg UpdateSubscriptionTierParams) error
	UpdateTeamMaxSeats(ctx context.Context, arg UpdateTeamMaxSeatsParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertStripeCustomer(ctx context.Context, arg UpsertStripeCustomerParams) error
}

var _ Querier = (*Queries)(nil)
