// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stripe_events.sql

package sqlcgen

import (
	"context"
)

const insertProcessedEvent = `-- name: InsertProcessedEvent :exec
INSERT INTO processed_stripe_events (event_id, event_type) VALUES ($1, $2)
`

type InsertProcessedEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) InsertProcessedEvent(ctx context.Context, arg InsertProcessedEventParams) error {
	_, err := q.db.Exec(ctx, insertProcessedEvent, arg.EventID, arg.EventType)
	return err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_stripe_events WHERE event_id = $1)
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
