// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stripe_customers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStripeCustomerByUserID = `-- name: GetStripeCustomerByUserID :one
SELECT user_id, customer_id, created_at
FROM stripe_customers
WHERE user_id = $1
`

func (q *Queries) GetStripeCustomerByUserID(ctx context.Context, userID pgtype.UUID) (StripeCustomer, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerByUserID, userID)
	var i StripeCustomer
	err := row.Scan(&i.UserID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const getUserIDByStripeCustomerID = `-- name: GetUserIDByStripeCustomerID :one
SELECT user_id
FROM stripe_customers
WHERE customer_id = $1
`

func (q *Queries) GetUserIDByStripeCustomerID(ctx context.Context, customerID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByStripeCustomerID, customerID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const upsertStripeCustomer = `-- name: UpsertStripeCustomer :exec
INSERT INTO stripe_customers (user_id, customer_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET customer_id = $2
`

type UpsertStripeCustomerParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CustomerID string      `json:"customer_id"`
}

func (q *Queries) UpsertStripeCustomer(ctx context.Context, arg UpsertStripeCustomerParams) error {
	_, err := q.db.Exec(ctx, upsertStripeCustomer, arg.UserID, arg.CustomerID)
	return err
}
