// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, joined_at
`

type AddTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, owner_id, max_seats)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, max_seats, created_at, updated_at
`

type CreateTeamParams struct {
	Name     string      `json:"name"`
	OwnerID  pgtype.UUID `json:"owner_id"`
	MaxSeats int32       `json:"max_seats"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.OwnerID, arg.MaxSeats)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.MaxSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamInvite = `-- name: CreateTeamInvite :one
INSERT INTO team_invites (team_id, email, invited_by, token, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, team_id, email, invited_by, token, status, created_at, expires_at
`

type CreateTeamInviteParams struct {
	TeamID    pgtype.UUID `json:"team_id"`
	Email     string      `json:"email"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	Token     string      `json:"token"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateTeamInvite(ctx context.Context, arg CreateTeamInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, createTeamInvite,
		arg.TeamID,
		arg.Email,
		arg.InvitedBy,
		arg.Token,
		arg.Status,
	)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.InvitedBy,
		&i.Token,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, owner_id, max_seats, created_at, updated_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.MaxSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByOwnerID = `-- name: GetTeamByOwnerID :one
SELECT id, name, owner_id, max_seats, created_at, updated_at
FROM teams
WHERE owner_id = $1
`

func (q *Queries) GetTeamByOwnerID(ctx context.Context, ownerID pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByOwnerID, ownerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.MaxSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByUserID = `-- name: GetTeamByUserID :one
SELECT t.id, t.name, t.owner_id, t.max_seats, t.created_at, t.updated_at
FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
`

func (q *Queries) GetTeamByUserID(ctx context.Context, userID pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByUserID, userID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.MaxSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamInviteByToken = `-- name: GetTeamInviteByToken :one
SELECT id, team_id, email, invited_by, token, status, created_at, expires_at
FROM team_invites
WHERE token = $1
`

func (q *Queries) GetTeamInviteByToken(ctx context.Context, token string) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, getTeamInviteByToken, token)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.InvitedBy,
		&i.Token,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, team_id, email, invited_by, token, status, created_at, expires_at
FROM team_invites
WHERE team_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvites(ctx context.Context, teamID pgtype.UUID) ([]TeamInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamInvite
	for rows.Next() {
		var i TeamInvite
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.InvitedBy,
			&i.Token,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.team_id, tm.user_id, tm.role, tm.joined_at, u.email
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.joined_at ASC
`

type ListTeamMembersRow struct {
	ID       pgtype.UUID        `json:"id"`
	TeamID   pgtype.UUID        `json:"team_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	Email    string             `json:"email"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateInviteStatus = `-- name: UpdateInviteStatus :exec
UPDATE team_invites SET status = $1 WHERE id = $2
`

type UpdateInviteStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) error {
	_, err := q.db.Exec(ctx, updateInviteStatus, arg.Status, arg.ID)
	return err
}

const updateTeamMaxSeats = `-- name: UpdateTeamMaxSeats :exec
UPDATE teams SET max_seats = $1, updated_at = NOW() WHERE id = $2
`

type UpdateTeamMaxSeatsParams struct {
	MaxSeats int32       `json:"max_seats"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTeamMaxSeats(ctx context.Context, arg UpdateTeamMaxSeatsParams) error {
	_, err := q.db.Exec(ctx, updateTeamMaxSeats, arg.MaxSeats, arg.ID)
	return err
}
